server:
  port: 8090

spring:
  messages:
    basename: messages
  application:
    name: zero-ddd-gateway
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
    gateway:
      routes:
        - id: zero-ddd-tenant
          uri: lb://zero-ddd-tenant
          order: 0
          predicates:
            - Path=/tenant/**
        - id: zero-ddd-main
          uri: lb://zero-ddd-main
          order: 0
          predicates:
            - Path=/main/**
        - id: zero-ddd-auth
          uri: lb://zero-ddd-auth
          order: 0
          predicates:
            - Path=/auth/**
        - id: zero-ddd-camunda
          uri: lb://zero-ddd-camunda
          order: 0
          predicates:
            - Path=/engine-rest/**

  redis:
    redisson:
      file: classpath:redisson.yml


#springdoc:
#  swagger-ui:
#    urls:
#      - name: tenant
#        url: /v3/api-docs/tenant
#      - name: main
#        url: /v3/api-docs/main

security:
  context:
    enabled-access: true
  filter:
    ignore-url:
      - /auth/login/username
      - /auth/logout
      - /auth/v1/captcha
      - /main/graphiql
      - /main/v1/user/detail
      - /main/v1/menu/resource/tree
      #      - /main/graphql
      #      - /tenant/graphql
    graphql:
      main-graphql:
        query:
          - findParameter
      tenant-graphql:
        query:
          - queryTenant

  jwt:
    enabled: true


