server:
  port: 8085

spring:
  application:
    name: zero-ddd-camunda
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-ddd?currentSchema=public
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false

  redis:
    redisson:
      file: classpath:redisson.yml

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:

management:
  endpoint:
    shutdown:
      access: UNRESTRICTED
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: shutdown

camunda:
  bpm:
    authorization:
      enabled: false  # 先禁用
    identity-provider:
      enabled: false   # 使用默认的

#camunda:
#  bpm:
#    admin-user:
#      id: demo
#      password: demo
#      firstName: Demo
#    filter:
#      create: All tasks
#    webapp:
#      index-redirect-enabled: false
#    job-execution:
#      enabled: true
#      core-pool-size: 5
#      wait-time-in-millis: 5000
#    authorization:
#      enabled: true
#      identity-provider:
#        enabled: true  # 禁用默认身份提供者


multi-tenancy:
  database: PostgreSQL
  database-pattern:
    url-prefix: "jdbc:postgresql://localhost:5432/"
  schema-pattern:
    schema: "PUBLIC"
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-tenant
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  context:
    enabledAccess: false