server:
  port: 8085

spring:
  application:
    name: zero-ddd-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-ddd?currentSchema=schema1
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false

  redis:
    redisson:
      file: classpath:redisson.yml

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:

management:
  endpoint:
    shutdown:
      access: UNRESTRICTED
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: shutdown


security:
  captcha:
    enable: true
    filter-url:
      - /auth/login/**
  context:
    enabled-access: false
    enabled-login-handler: true
  username-login:
    enabled: true
    login-path: /auth/login/username
  logout-path: /auth/logout


multi-tenancy:
  database: PostgreSQL
  database-pattern:
    url-prefix: "jdbc:postgresql://localhost:5432/"
  schema-pattern:
    schema: "PUBLIC"
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-tenant
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
