server:
  port: 8082

spring:
  application:
    name: zero-ddd-main
  modulith:
    detection-strategy: explicitly-annotated
    events:
      republish-outstanding-events-on-restart: true
      externalization:
        enabled: true
      completion-mode: archive
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    type: com.zaxxer.hikari.HikariDataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-ddd
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: PostgreSQL
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
    # 如下配置是被spring.datasource赋值的，所以可以不配置
    #    url: jdbc:mysql://localhost:3306/test_db_liquibase?useSSL=false&autoReconnect=true&characterEncoding=utf8
    #    user: root
    #    password: bfXa4Pt2lUUScy8jakXf
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  graphql:
#    cors:
#      allow-credentials: true
#      allowed-origins:
#        - http://localhost:5173
    schema:
      inspection:
        enabled: false
      introspection:
        enabled: false
    graphiql:
      enabled: true
      path: /main/graphiql
    path: /main/graphql

  redis:
    redisson:
      file: classpath:redisson.yml


springdoc:
  api-docs:
    enabled: true    # 确保 API 文档启用
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 访问路径

management:
  endpoint:
    rbac:
      access: UNRESTRICTED
    shutdown:
      access: UNRESTRICTED
  endpoints:
    web:
      base-path: /main/actuator
      exposure:
        include: shutdown, rbac

multi-tenancy:
  database: PostgreSQL
  database-pattern:
    url-prefix: "jdbc:postgresql://localhost:5432/"
  schema-pattern:
    schema: "PUBLIC"
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-tenant
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  key: dkhssdhheidjghosdhgkdhiebds

security:
  context:
    enabled-access: false


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error