--liquibase formatted sql


set client_min_messages = WARNING
;
alter table if exists main_expression
drop constraint if exists FKctm6ra2vx8wonfimyyf43tu35
;
alter table if exists main_graphql_resource
drop constraint if exists FKba3t1qhalxs85xw744xhfkby0
;
alter table if exists main_menu_resource
drop constraint if exists FKnf9umup3ovmj8d4wxios052ol
;
alter table if exists main_menu_resource
drop constraint if exists FK7o9nu5t5if0l5srsrpn6kkwi0
;
alter table if exists main_permission
drop constraint if exists FKknpo5mbi3jse1kmmgttpq3ik3
;
alter table if exists main_role_permission
drop constraint if exists FK6xefdd10oy6ts32yh5i6p63xx
;
alter table if exists main_role_permission
drop constraint if exists FK4asijil0617ps9gpyhthj65l
;
alter table if exists main_role_precondition
drop constraint if exists FKr0hofiv39ejgje1jj2f8aqa0x
;
alter table if exists main_user_expression
drop constraint if exists FKdaece98rnvyyciv9mf6lymrob
;
alter table if exists main_user_group_role
drop constraint if exists FKba52gdf7iis4ujq39g7ritlup
;
alter table if exists main_user_group_role
drop constraint if exists FKa7p2kin11wimpkjdvvu2c29ot
;
alter table if exists main_user_group_user
drop constraint if exists FKnctduxmn3df72yi5ixsf8jgdm
;
alter table if exists main_user_group_user
drop constraint if exists FK5sbc9pkxa4oqdpp2adktkc8u7
;
alter table if exists main_user_resource
drop constraint if exists FKc2vhxjnijdiarqfe9p7pmp2ui
;
alter table if exists main_user_role
drop constraint if exists FKqjyi9j8fbvtms7nkuca66twql
;
alter table if exists main_user_role
drop constraint if exists FKb2446vrjljcnwmw5ql8hnof0t
;
drop table if exists main_expression cascade
    ;
drop table if exists main_graphql_resource cascade
    ;
drop table if exists main_menu_resource cascade
    ;
drop table if exists main_parameter cascade
    ;
drop table if exists main_permission cascade
    ;
drop table if exists main_resource cascade
    ;
drop table if exists main_role cascade
    ;
drop table if exists main_role_permission cascade
    ;
drop table if exists main_role_precondition cascade
    ;
drop table if exists main_user cascade
    ;
drop table if exists main_user_expression cascade
    ;
drop table if exists main_user_group cascade
    ;
drop table if exists main_user_group_role cascade
    ;
drop table if exists main_user_group_user cascade
    ;
drop table if exists main_user_resource cascade
    ;
drop table if exists main_user_role cascade
    ;
drop table if exists main_user_session cascade
    ;
drop sequence if exists main_resource_seq
    ;
create sequence main_resource_seq start with 1 increment by 50
    ;
create table main_expression (
                                 created_date timestamp(6),
                                 id bigint generated by default as identity,
                                 last_modified_date timestamp(6),
                                 resource_id bigint,
                                 created_by varchar(255),
                                 last_modified_by varchar(255),
                                 tenant_by varchar(255) not null,
                                 primary key (id)
)
    ;
create table main_graphql_resource (
                                       id bigint not null,
                                       operation varchar(255),
                                       primary key (id)
)
    ;
create table main_menu_resource (
                                    enable boolean,
                                    resource_order integer,
                                    show boolean,
                                    id bigint not null,
                                    parent_id bigint,
                                    code varchar(255),
                                    component varchar(255),
                                    description varchar(255),
                                    icon varchar(255),
                                    keep_alive varchar(255),
                                    layout varchar(255),
                                    method varchar(255),
                                    name varchar(255),
                                    path varchar(255),
                                    redirect varchar(255),
                                    type varchar(255),
                                    primary key (id)
)
    ;
create table main_parameter (
                                created_date timestamp(6),
                                id bigint generated by default as identity,
                                last_modified_date timestamp(6),
                                created_by varchar(255),
                                last_modified_by varchar(255),
                                parameter_key varchar(255),
                                parameter_name varchar(255),
                                parameter_type varchar(255),
                                parameter_value varchar(255),
                                remark varchar(255),
                                tenant_by varchar(255) not null,
                                primary key (id)
)
    ;
create table main_permission (
                                 created_date timestamp(6),
                                 id bigint generated by default as identity,
                                 last_modified_date timestamp(6),
                                 resource_id bigint unique,
                                 code varchar(255),
                                 created_by varchar(255),
                                 last_modified_by varchar(255),
                                 tenant_by varchar(255) not null,
                                 primary key (id)
)
    ;
create table main_resource (
                               created_date timestamp(6),
                               id bigint not null,
                               last_modified_date timestamp(6),
                               resource_type varchar(31) not null,
                               created_by varchar(255),
                               last_modified_by varchar(255),
                               tenant_by varchar(255) not null,
                               primary key (id)
)
    ;
create table main_role (
                           deleted integer,
                           enable boolean,
                           role_sort integer,
                           created_date timestamp(6),
                           id bigint generated by default as identity,
                           last_modified_date timestamp(6),
                           code varchar(255),
                           created_by varchar(255),
                           last_modified_by varchar(255),
                           name varchar(255),
                           tenant_by varchar(255) not null,
                           primary key (id)
)
    ;
create table main_role_permission (
                                      created_date timestamp(6),
                                      id bigint generated by default as identity,
                                      last_modified_date timestamp(6),
                                      permission_id bigint,
                                      role_id bigint,
                                      created_by varchar(255),
                                      last_modified_by varchar(255),
                                      tenant_by varchar(255) not null,
                                      primary key (id)
)
    ;
create table main_role_precondition (
                                        created_date timestamp(6),
                                        id bigint generated by default as identity,
                                        last_modified_date timestamp(6),
                                        role_id bigint,
                                        created_by varchar(255),
                                        last_modified_by varchar(255),
                                        tenant_by varchar(255) not null,
                                        primary key (id)
)
    ;
create table main_user (
                           deleted integer,
                           created_date timestamp(6),
                           id bigint generated by default as identity,
                           last_modified_date timestamp(6),
                           avatar varchar(255),
                           created_by varchar(255),
                           email varchar(255),
                           gender varchar(255),
                           last_modified_by varchar(255),
                           nick_name varchar(255),
                           password varchar(255),
                           phone_number varchar(255),
                           status varchar(255),
                           tenant_by varchar(255) not null,
                           username varchar(255),
                           primary key (id)
)
    ;
create table main_user_expression (
                                      created_date timestamp(6),
                                      id bigint generated by default as identity,
                                      last_modified_date timestamp(6),
                                      user_resource_id bigint,
                                      created_by varchar(255),
                                      last_modified_by varchar(255),
                                      tenant_by varchar(255) not null,
                                      primary key (id)
)
    ;
create table main_user_group (
                                 created_date timestamp(6),
                                 id bigint generated by default as identity,
                                 last_modified_date timestamp(6),
                                 created_by varchar(255),
                                 last_modified_by varchar(255),
                                 tenant_by varchar(255) not null,
                                 primary key (id)
)
    ;
create table main_user_group_role (
                                      created_date timestamp(6),
                                      id bigint generated by default as identity,
                                      last_modified_date timestamp(6),
                                      role_id bigint,
                                      user_group_id bigint,
                                      created_by varchar(255),
                                      last_modified_by varchar(255),
                                      tenant_by varchar(255) not null,
                                      primary key (id)
)
    ;
create table main_user_group_user (
                                      created_date timestamp(6),
                                      id bigint generated by default as identity,
                                      last_modified_date timestamp(6),
                                      user_group_user_id bigint,
                                      user_id bigint,
                                      created_by varchar(255),
                                      last_modified_by varchar(255),
                                      tenant_by varchar(255) not null,
                                      primary key (id)
)
    ;
create table main_user_resource (
                                    created_date timestamp(6),
                                    id bigint generated by default as identity,
                                    last_modified_date timestamp(6),
                                    user_id bigint,
                                    created_by varchar(255),
                                    last_modified_by varchar(255),
                                    tenant_by varchar(255) not null,
                                    primary key (id)
)
    ;
create table main_user_role (
                                created_date timestamp(6),
                                id bigint generated by default as identity,
                                last_modified_date timestamp(6),
                                role_id bigint,
                                user_id bigint,
                                created_by varchar(255),
                                last_modified_by varchar(255),
                                tenant_by varchar(255) not null,
                                primary key (id)
)
    ;
create table main_user_session (
                                   created_date timestamp(6),
                                   id bigint generated by default as identity,
                                   last_modified_date timestamp(6),
                                   created_by varchar(255),
                                   last_modified_by varchar(255),
                                   tenant_by varchar(255) not null,
                                   primary key (id)
)
    ;
alter table if exists main_expression
    add constraint FKctm6ra2vx8wonfimyyf43tu35
    foreign key (resource_id)
    references main_resource
    ;
alter table if exists main_graphql_resource
    add constraint FKba3t1qhalxs85xw744xhfkby0
    foreign key (id)
    references main_resource
    ;
alter table if exists main_menu_resource
    add constraint FKnf9umup3ovmj8d4wxios052ol
    foreign key (parent_id)
    references main_menu_resource
    ;
alter table if exists main_menu_resource
    add constraint FK7o9nu5t5if0l5srsrpn6kkwi0
    foreign key (id)
    references main_resource
    ;
alter table if exists main_permission
    add constraint FKknpo5mbi3jse1kmmgttpq3ik3
    foreign key (resource_id)
    references main_resource
    ;
alter table if exists main_role_permission
    add constraint FK6xefdd10oy6ts32yh5i6p63xx
    foreign key (permission_id)
    references main_permission
    ;
alter table if exists main_role_permission
    add constraint FK4asijil0617ps9gpyhthj65l
    foreign key (role_id)
    references main_role
    ;
alter table if exists main_role_precondition
    add constraint FKr0hofiv39ejgje1jj2f8aqa0x
    foreign key (role_id)
    references main_role
    ;
alter table if exists main_user_expression
    add constraint FKdaece98rnvyyciv9mf6lymrob
    foreign key (user_resource_id)
    references main_user_resource
    ;
alter table if exists main_user_group_role
    add constraint FKba52gdf7iis4ujq39g7ritlup
    foreign key (role_id)
    references main_role
    ;
alter table if exists main_user_group_role
    add constraint FKa7p2kin11wimpkjdvvu2c29ot
    foreign key (user_group_id)
    references main_user_group
    ;
alter table if exists main_user_group_user
    add constraint FKnctduxmn3df72yi5ixsf8jgdm
    foreign key (user_id)
    references main_user
    ;
alter table if exists main_user_group_user
    add constraint FK5sbc9pkxa4oqdpp2adktkc8u7
    foreign key (user_group_user_id)
    references main_user_group
    ;
alter table if exists main_user_resource
    add constraint FKc2vhxjnijdiarqfe9p7pmp2ui
    foreign key (user_id)
    references main_user
    ;
alter table if exists main_user_role
    add constraint FKqjyi9j8fbvtms7nkuca66twql
    foreign key (role_id)
    references main_role
    ;
alter table if exists main_user_role
    add constraint FKb2446vrjljcnwmw5ql8hnof0t
    foreign key (user_id)
    references main_user
    
insert into
    main_user
(deleted, password, status, tenant_by, username)
values
    (0, '{bcrypt}$2a$10$8xbX8CngT8AO8froAt8Ky.VDSzhxSFpIZlp4aO.XKnX3g3tGbj/QO', '0', '${tenantName}', 'superAdmin');
insert into
    main_user
(deleted, password, status, tenant_by, username)
values
    (0, '{bcrypt}$2a$10$8xbX8CngT8AO8froAt8Ky.VDSzhxSFpIZlp4aO.XKnX3g3tGbj/QO', '0', '${tenantName}', 'admin');
insert into
    main_user
(deleted, password, status, tenant_by, username)
values
    (0, '{bcrypt}$2a$10$mbJbeoem4jwjn2ADRQHqQeyy39SHnn37.TNsWknBA8upQzdhWUPQK', '0', '${tenantName}', 'root');


insert into
    main_role
(deleted, role_sort, enable, code, name, tenant_by)
values
    (0, 0, 'true', 'admin', '管理员', '${tenantName}');

insert into
    main_user_role
(role_id, user_id, tenant_by)
values
    (1, 2, '${tenantName}');

insert into
    main_user_role
(role_id, user_id, tenant_by)
values
    (1, 3, '${tenantName}');